

logging.file: logs/application.log
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
spring:
  datasource:
    url:  jdbc:h2:file:./h2/org
  jpa:
    hibernate:
      #      ddl-auto: none
      ddl-auto: validate
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:.db/migration



server:
  port: 8888